version: "3"
services: 
  client: 
    container_name: client 
    build: 
      context: . 
      dockerfile: DockerfileClient
    image: hsim0203/react-map 
    ports: 
      - "80:3000"
  server: 
    container_name: server 
    build: 
      context: . 
      dockerfile: DockerfileServer
    image: hsim0203/express-server 
    ports: 
      - "4000:4000"
